[package]
name = "rust-gdb-test"
version = "0.1.0"
authors = ["wantlord"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
